echo deleting old logs...
sudo rm *.log
echo git pulling...
git pull origin main            &> gitpull.log
# comment out the next few lines to enable ssh and disable the controller hotspot
echo starting hotspot...
sudo bash ./create_hotspot.sh   &> hotspotcreate.log
echo starting python, ssh would\'ve disconnected by now
sudo python -u ./web.py         &> pythonwebstuff.log
